src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 191, nullable: true)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 191)]
    private $Nom;

    #[ORM\OneToMany(mappedBy: 'NomAuteur', targetEntity: Formation::class, orphanRemoval: true)]
    private $formations;

    #[ORM\Column(type: 'string', length: 191, nullable: true)]
    private $photo;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Progression::class)]
    private $progressions;

    public function __construct()
    {
        $this->formations = new ArrayCollection();
        $this->progressions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormation(Formation $formation): self
    {
        if (!$this->formations->contains($formation)) {
            $this->formations[] = $formation;
            $formation->setNomAuteur($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): self
    {
        if ($this->formations->removeElement($formation)) {
            // set the owning side to null (unless already changed)
            if ($formation->getNomAuteur() === $this) {
                $formation->setNomAuteur(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Progression>
     */
    public function getProgressions(): Collection
    {
        return $this->progressions;
    }

    public function addProgression(Progression $progression): self
    {
        if (!$this->progressions->contains($progression)) {
            $this->progressions[] = $progression;
            $progression->setUser($this);
        }

        return $this;
    }

    public function removeProgression(Progression $progression): self
    {
        if ($this->progressions->removeElement($progression)) {
            // set the owning side to null (unless already changed)
            if ($progression->getUser() === $this) {
                $progression->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/MoncompteController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Repository\FormationRepository;
use App\Repository\ProgressionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MoncompteController extends AbstractController
{
    #[Route('/moncompte', name: 'app_moncompte')]
    public function details(FormationRepository $formationRepository, ProgressionRepository $progressionRepository): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        return $this->render('moncompte/index.html.twig', [
            'formations' => $formationRepository->countByFormation(),
            'progressions' =>$progressionRepository->findByUser($user->getId()), 
            
        ]);
        
    }

    
}

templates/moncompte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}
<main class="container">
  <div class="connexion">
    <h2>Mon Compte</h2>
  </div>
  <section class="row justify-content-center">
    <aside class="col-4">
      <div class="row justify-content-center">
        <img class="col-8" src="{{ asset('assets/ressources/abstract.jpg') }}" alt="">              
      </div>
    </aside>
    <div class="col-lg-4">
      <div class="row justify-content-center align-items-center">                  
        <div class="col-12 connexion">
          <div class="pageco">
            <h4>Mon profil</h4>
            <div>Nom : {{app.user.nom}} {{app.user.prenom}}</div>
            <div>Email : {{app.user.email}}</div>
            {% if app.user.photo != null %}
            <div><img class="img-profil" src="{{ asset('upload/photoprofil/') }}{{ app.user.photo }}"></div>
            {% endif %}
          </div>
        </div>
        <img class="col-12" src="{{ asset('assets/ressources/webinar.jpg') }}" alt="">
        <div class="col-12 connexion">    
              {% if is_granted('ROLE_SUPER_ADMIN') %}
                  <h4>Gestion administrateur</h4>
                  <button class="connectbtn"><a href="{{ path('app_admin') }}">ADMIN</a></button>        
              {% elseif is_granted('ROLE_INSTRUCTEUR') %}
                  <h4>Mes formations</h4>
                  <button class="connectbtn"><a href="{{ path('app_create_forma_index') }}">Voir mes formations</a></button>
                  <button class="connectbtn"><a href="{{ path('app_create_forma_new') }}">Créer une nouvelle formation</a></button>
              {% elseif is_granted('ROLE_USER') %}
                  <h4>Ma progression</h4>
                  <div>                  
                  {% set resultprog = progressions|length * 100 / formations %}
                  
                  </div>
                  <div class="progress">
                    <div class="progress-bar bg-info" role="progressbar" style="width: {{ resultprog|round}}%"aria-valuenow="{{ resultprog|round}}" aria-valuemin="0" aria-valuemax="100">{{ resultprog|round}} %</div>
                  </div>        
              {% endif %}
        </div>
      </div>
    </div>
    <aside class="col-4">
      <div class="row justify-content-center">
        <img class="col-6" src="{{ asset('assets/ressources/tux.png') }}" alt="">
      </div>
      <div class="row justify-content-center connexion">
        <img class="col-6" src="{{ asset('assets/ressources/pixel.png') }}" alt="">              
      </div>
    </aside>
  </section>
</main>

{% endblock %}